name = "Belledelphia 2.0"
author = "Mason Besmer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9be01a3c0dfbae0d40df79bdca12a753e086aaa2e142bbfdf81f3dde2968004"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
