name = "Belledelphia 2.0"
author = "Mason Besmer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9c8b31ac0ef08129d16fe2888b6079725264ad6dde30a9e7e5f6637a5e7c64d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
